### ISSUE TITLE
Make `dstack config` per repository (but still keep it under `~/.dstack` folder)

### ISSUE THREAD

**Issue by eafpres** [dstackai/dstack#106]
Current behavior:
Running dstack config over-writes the global config.yaml file
Desired behavior:
Create config.yaml per repo / project
This facilitates running different jobs in different regions, using different accounts, etc.

**Comment by eafpres** [comment]
FYI, a feature I would like here is that when you enter a profile in config, it looks at it and proposes that region (if in the profile) as the target.  As it is now, it seems to always propose the currently configured region.

**Comment by peterschmidt85** [comment]
> FYI, a feature I would like here is that when you enter a profile in config, it looks at it and proposes that region (if in the profile) as the target. As it is now, it seems to always propose the currently configured region.

Made a separate issue (#128)

**Comment by peterschmidt85** [comment]
Here's how we consider implementing it.

1. The new default behavior of `dstack config` will imply saving the `.dstack/config.yaml` inside the repo. Basically, `workflows.yaml` and `config.yaml` will be next to each other.

2. If the user would like to configure it globally, the user would have to use `dstack config --global`.

3. When other `dstack` CLI commands will be called, it will try to use the config from the current repo if any, and the global one otherwise.

Let me know if this makes sense!

Also, please let me know if this feature is a blocker for you. If so, we'll include to `v0.0.14`.

**Comment by eafpres** [comment]
The proposed behavior sounds good.  
This is not a blocker, so it can be done any time.

**Comment by r4victor** [comment]
After moving to the Hub-only model (#338), you can create multiple projects in Hub and configure the CLI to work with all of them (#354).
