### ISSUE TITLE
[Feature]: Check the VPC validity on server startup

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1157]
### Problem

Currently, if I set up an AWS backend and start the server, I don't see if I configured the VPC correctly. Because the VPC is configured by the admin, the admin should see if it was configured correctly.

### Solution

- The server on startup should check if the specified VPCs are available in the configured regions and are public. 
- If VPC is not configured, the server should check that the default VPC exists in the configured regions and is public.

### Would you like to help us implement this feature by sending a PR?

Yes

**Comment by r4victor** [comment]
Note that vpc should be checked when launching instance anyway since the vpc configuration may change after backend configuration.

Also, checking that VPCs in all regions have public subnets may take some time due to many network requests. The checks in different regions have to be done in parallel.
