### ISSUE TITLE
[UX] Show fleet creation errors on the CLI side

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1637]
**Steps to reproduce:**

1. Create an on-prem fleet using an SSH key with a passphrase

**Actual behavior:**

1. Fleet is not created
2. Server logs:

```
Failed to start instance ep-onprem-0: private SSH key is encrypted
```

**Expected behavior:**

1. This error is shown on the CLI side and not on the server side

**Notes:**

1. #1571 The attached mode when creating a fleet will improve UX too

2. The same problem occurs, e.g. if I specified a wrong `network`:

```
Failed to configure internal ip-address on instance fleet-on-prem-0. Terminate it
```

**Comment by r4victor** [comment]
#1661 adds ssh key validation so that the errors are shown on `dstack apply`.

Unfortunately, network cannot be validated at submission time since it requires fetching all instances interfaces. Instance processing doesn't implement a mechanism to pass errors to the CLI after the submission. A correct error handling will require keeping FAILED instances with appropriate error status (currently they are terminated and removed on error). This should be addressed in #1662.
