### ISSUE TITLE
[Bug]: Task freezes and fails without any notification

### ISSUE THREAD

**Issue by rodrigomeireles** [dstackai/dstack#1654]
### Steps to reproduce

Dsky user: rodrigomeireles
Dsky project: financial-assistant
Dsky run name: modern-bear-1

### Actual behaviour

My run froze installing torch. This is not the first time this happened. No meaningful log was outputted. My ran was logged as an error. This is a random event so there are no steps to reproduce.

### Expected behaviour

If the run failed for some reason, some message should be logged.

### dstack version

0.18.11

**Comment by r4victor** [comment]
@rodrigomeireles, You can check run termination reason with `dstack ps -v` or via the API. 

The `modern-bear-1` run terminated with INTERRUPTED_BY_NO_CAPACITY which typically happens when the cloud interrupts spot instances. Since the run was using a spot instance, this can be expected. Use `on-demand` [spot policy](https://dstack.ai/docs/reference/dstack.yml/task/#spot-policy) to provision only on-demand instances.

Probably another point for #1650.

**Comment by r4victor** [comment]
Closing as https://github.com/dstackai/dstack/issues/1650 should solve it.
