### ISSUE TITLE
[Feature]: Support `docker` and `docker compose` commands 

### ISSUE THREAD

**Issue by aleksandr-smechov** [dstackai/dstack#1668]
### Problem

dstack currently doesn't allow you to use docker in runs. 

### Solution

As @peterschmidt85 suggests, something like the below would be helpful for running `docker` and `docker compose` commands:

```
docker: true
```

### Would you like to help us implement this feature by sending a PR?

No

**Comment by un-def** [comment]
As runs are already executed inside Docker containers, using `docker`/`docker compose` would require running Docker in Docker (dind), which:

* requires privileged mode, even with rootless dind, with consequent security implications;
* won't work with GPUs, at least out-of-the-box, and there is no official guide how to make it work (there are a couple of third-party projects, but all of them are based on the deprecated `nvidia-docker`, not NVIDIA Container Toolkit, and `dstack` supports not only Nvidia, but also AMD GPUs and Google TPUs).

**Comment by un-def** [comment]
Since [0.18.18](https://github.com/dstackai/dstack/releases/tag/0.18.18) it's possible to use `docker`/`docker compose` with `dstack` as described [here](https://dstack.ai/docs/guides/protips/#docker-and-docker-compose). If this feature is still relevant for you, please give it a try and let us know if you have any issues.

**Comment by aleksandr-smechov** [comment]
Thanks for the update!

Sent via Superhuman ***@***.***>
