### ISSUE TITLE
[Feature] Switch from per-run certificates to wildcard per-project certificates

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1797]
1. Easier to use with Let's Encrypt (the default implementation) – no "Certificates per Registered Domain (50 per week)" limit;
2. Both Let's Encrypt and ZeroSSL can experience outages, which may disrupt service submissions.

**Comment by r4victor** [comment]
The main reason we didn't support wildcard certificates initially is that they do not support HTTP-01 challenge that we can easily automate but only DNS-01 challenge.

Automating DNS-01 challenge is problematic since it would only work with DNS providers explicitly supported by dstack.

And I argue many users would not give dstack control over their DNS zones for policy reasons.

The alternative solution could be having a backup ACME issuer in case of the primary issuer downtimes – this would work both for Sky and OSS users.
