### ISSUE TITLE
[Feature]: Ability to run privileged containers for Docker-in-Docker support

### ISSUE THREAD

**Issue by mtaran** [dstackai/dstack#1820]
### Problem

Currently if you try to run a DinD container like what you get from [here](https://github.com/ehfd/nvidia-dind), it doesn't work because dstack generally launches containers without the `--privileged` docker flag. That flag is necessary for DinD to work.

### Solution

Could add an env var or yaml flag to run containers with `--privileged`.

### Workaround

No.

### Would you like to help us implement this feature by sending a PR?

Yes

**Comment by un-def** [comment]
Since [0.18.18](https://github.com/dstackai/dstack/releases/tag/0.18.18) it's possible to use `docker`/`docker compose` with `dstack` as described [here](https://dstack.ai/docs/guides/protips/#docker-and-docker-compose). It works with NVIDIA GPUs and should work with AMD GPUs if a container is created with AMD-specific requirements (`--device` mounts, `--group-add` user groups).
