### ISSUE TITLE
`dstack ls` fails on macOS and Windows if an artifact contains "case-sensitive" symlinks

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#189]
**Describe the bug**
Running `dstack ls` on large artifacts (Conda env in this case) throws an error: `OSError: [Errno 62] Too many levels of symbolic links` (see screenshot and logs below)

**Version**
 - The `dstack` CLI version 0.1
 - The operational system version Apple M2 MacOS 13.1
 - The Python version 3.10.4
- (Optional) Other Python packages versions (`pip freeze` or `conda list`)

**Minimal example**
Source code https://github.com/kengz/lean-dl-example/commit/f4c06f0c59bc9d945c64bf53c7df0c26c029d67b

**Steps to reproduce**
- `dstack run setup-conda`
- wait for completion
- `dstack ls great-starfish-0` (or whatever the run name is)

**Expected behavior**
Shows the conda env folder

**Logs**

[a82a3ec14d6f463cb76e83261598d865.zip](https://github.com/dstackai/dstack/files/10717321/a82a3ec14d6f463cb76e83261598d865.zip)

**Screenshots**
<img width="730" alt="Screenshot 2023-02-12 at 4 11 08 PM" src="https://user-images.githubusercontent.com/8209263/218337471-d66047ad-75f3-4f19-ad4c-89fc7ab37278.png">

**Additional context**

**Comment by peterschmidt85** [comment]
Additional context:

According to https://github.com/conda/conda/issues/10333#issuecomment-1340682188,  the problem is caused by loading a package that is designed for a file system that is case-sensitive (i.e. Linux) onto a filesystem that is case-insensitive (i.e. macOS or Windows).

```shell
ls -l /Users/cheptsov/.dstack/artifacts/github.com/kengz/lean-dl-example/tasty-warthog-0,setup-conda,0/opt/conda/envs/dl/share/terminfo/N/ncr260vt300wpp
lrwxr-xr-x  1 cheptsov  staff  19 Feb 17 13:26 /Users/cheptsov/.dstack/artifacts/github.com/kengz/lean-dl-example/tasty-warthog-0,setup-conda,0/opt/conda/envs/dl/share/terminfo/N/ncr260vt300wpp -> ../N/NCR260VT300WPP
```

**Comment by peterschmidt85** [comment]
Implementation notes:

Similar to `ls` in Linux, in `dstack ls`, for symlinks, the size should represent the size of the symlink and not the actual file. Thus, the command should use `os.stat(..., follow_symlinks=False).st_size` instead of `os.path.getsize(...)`.

Additional information:

1.  https://github.com/dstackai/dstack/issues/180 Currently, `dstack` may sometimes not handle symlinks properly. Though we haven't seen any issues related to symlink in Conda yet, this should be kept in mind.
2. https://github.com/dstackai/dstack/issues/131 There is a plan to change the default behavior of the `dstack ls` command to make it not recursive by default. In the context of this issue, it makes sense to change the `dstack ls` command to display if the file is a symlink.
