### ISSUE TITLE
Run failed if the user is using an RSA key for SSH

### ISSUE THREAD

**Issue by Yorko** [dstackai/dstack#197]
Reproducing all steps described [here](https://github.com/dstackai/dstack-examples/tree/main/stable_diffusion) for stable diffusion. 

`dstack run stable-diffusion` takes just 7-10 secs. to finish

<img src="https://habrastorage.org/webt/ht/x9/kq/htx9kq3uar1xngyhv0p4ae-6kta.png" />

> Once you run it, dstack will run the script, and save the models folder as an artifact. After that, you can reuse it in other workflows.

This doesn't happen. 

`dstack ps` shows that the run is failed although no logs are anywhere to be seen.

<img src="https://habrastorage.org/webt/ld/or/jr/ldorjrply3hi6ass1o3d2cgu3x0.png" />

[Here](https://drive.google.com/file/d/1kIdCZfwwTy-bSEfr5zeuDjSR0Myy21sJ/view?usp=sharing) are the contents of the `~/.dstack/tmp/runner/configs` folder.

Tested with both Mac OS X 11.7 with Python 3.10.9 and dstack 0.1 and Ubuntu 20.04.5 LTS with Python 3.8.10 and dstack 0.1

**Comment by r4victor** [comment]
The issue happens when using `ssh-rsa` keys for github auth. The runner prints:
```
time=2023-02-17T16:10:52+05:00 level=error msg=Failed run err=[executor.go:216 executor.(*Executor).runJob] [executor.go:325 executor.(*Executor).prepareGit] unknown error: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.
```

OpenSSH ended support for SHA-1 signatures ("ssh-rsa" signatures) but the keys should still work:

> "ssh-rsa" keys are capable of signing using "rsa-sha2-256" (RSA/SHA256), "rsa-sha2-512" (RSA/SHA512)

The problem is that our current version of `golang.org/x/crypto` is not capable of that (https://github.com/go-git/go-git/issues/516). The latest version is, so the update fixes the issue and `ssh-rsa` keys work.
