### ISSUE TITLE
[Feature]: Build platform-dependant wheel packages that bundle the runner

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#256]
### Problem

Currently, if I install `dstack` and run a workflow locally, it downloads the `runner`. This means the first run will be slow, and if the user has no internet, may not work at all.

### Solution

Bundle the `runner` binary into the wheel package. Here's an example: https://pypi.org/project/playwright/#files

### Benefit

The getting started experience will be much better. 

### Alternatives

Not I'm aware of.

### Would you like to help contributing this feature?

Yes

**Comment by r4victor** [comment]
This doesn't make much sense since the runner is required only for local backend. And in this case, the runner is not a large dependency compared to docker images – 70Mb vs 1.7Gb. After moving to the Hub-only model (https://github.com/dstackai/dstack/issues/338), it's even better that the runner is optional since users may need only the CLI.
